#!/bin/sh
# /etc/init.d/motion
# Start/stop/restart
motion_start() {
if [ -x /usr/bin/motion ]; then
mount server:/securecam/snapshots /home/fbcop/snapshots
killall motion
sleep 5
echo "Starting Motion"
su fbcop -c /usr/bin/motion &
fi
}
motion_stop() {
echo "Stopping motion"
sudo killall motion
}
motion_restart() {
motion_stop
sleep 2
motion_start
}
case "$1" in
'start')
motion_start
;;
'stop')
motion_stop
;;
'restart')
motion_restart
;;
*)
motion_start
esac
